Vagrant.configure(2) do |config|

    config.vm.define "pllucianS" do |server|
        server.vm.box = "debian/bullseye64"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "pllucianS"
            vb.cpus = 1
            vb.memory = 1024
        end
        server.vm.hostname = "pllucianS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provision "shell", path: "scripts/k3s-server.sh"
    end

    config.vm.define "pllucianSW" do |server|
        server.vm.box = "debian/bullseye64"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "pllucianSW"
            vb.cpus = 1
            vb.memory = 1024
        end
        server.vm.hostname = "pllucianSW"
        server.vm.network "private_network", ip: "192.168.56.111"
        server.vm.provision "shell", path: "scripts/k3s-agent.sh"
    end

end
