Vagrant.configure(2) do |config|

    config.vm.define "pllucianS" do |server|
        server.vm.box = "debian/bullseye64"
        server.vm.provider "virtualbox" do |vb|
            vb.name = "pllucianS"
            vb.cpus = 4
            vb.memory = 8192
        end
        server.vm.hostname = "pllucianS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provision "shell", path: "scripts/k3d-cluster.sh"
        server.vm.provision "shell", path: "scripts/apps.sh"
    end

end
